name: clima
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  font_awesome_flutter: ^8.8.1
  geolocator: ^5.3.1
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  # assets:
  # - images/

  fonts:
  - family: Monserrat
    fonts:
    - asset: fonts/Montserrat-Regular.ttf
      weight: 400
    - asset: fonts/Montserrat-ExtraBold.ttf
      weight: 800